# -*- coding: utf-8 -*-
"""deep-learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wn19NDr44tkvpNhhHqoXwklM8pN1vo4_
"""

import numpy as np
print(np.__version__) # doit afficher 1.x ou 2.x, pas une erreur

"""Phase 1 : Neurone unique, forward pass et calcul d'erreur

"""

import numpy as np

# Données d'entrée (4 points en 2D)
X = np.array([
    [0.2, 0.1],
    [0.8, 0.9],
    [0.3, 0.7],
    [0.9, 0.2],
])
y = np.array([0, 1, 1, 0])

def sigmoid(x):
    """Fonction d'activation pour transformer la sortie en probabilité (0 à 1)."""
    return 1 / (1 + np.exp(-x))

def forward(X, w, b):
    """Calcule la sortie du neurone : z = Xw + b, puis activation."""
    z = np.dot(X, w) + b
    return sigmoid(z)

def compute_loss(y_true, y_pred):
    """Calcule l'erreur via la Binary Cross-Entropy."""
    # On évite log(0) ou log(1) qui renvoient NaN ou Inf
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    term_0 = y_true * np.log(y_pred)
    term_1 = (1 - y_true) * np.log(1 - y_pred)
    return -np.mean(term_0 + term_1)

# --- TEST SCÉNARIO INITIAL ---
w = np.array([0.5, -0.3])
b = 0.1

y_pred = forward(X, w, b)
loss = compute_loss(y, y_pred)

print(f"--- Scénario Fixe ---")
print(f"Prédictions : {y_pred.round(3)}")
print(f"Étiquettes  : {y}")
print(f"Loss BCE     : {loss:.4f}")

# --- TEST SCÉNARIO ADVERSARIAL (Poids à zéro) ---
w_zero = np.zeros(2)
b_zero = 0
y_pred_zero = forward(X, w_zero, b_zero)
loss_zero = compute_loss(y, y_pred_zero)

print(f"\n--- Scénario Adversarial (Zéro) ---")
print(f"Prédictions : {y_pred_zero}")
print(f"Loss BCE     : {loss_zero:.4f} (Doit être proche de 0.693)")



